query param to JavaBean
fivesmallq/play1-base pull request #11
Opened 2019-04-24 16:19 UTC by xinput123

too many parameters in the GET method

2019-04-26 01:29 UTC, fivesmallq requested changes

2019-04-26 01:29 UTC, fivesmallq commented on api/app/controllers/api/API.java
> +        }
整体这个方法的处理还是有点粗糙，可以参考apache httpclient的URLEncodedUtils.parse方法试试

2019-04-26 01:29 UTC, fivesmallq commented on api/app/controllers/api/API.java
> +        }
https://github.com/apache/httpcomponents-core/blob/master/httpcore5/src/main/java/org/apache/hc/core5/net/URLEncodedUtils.java#L115

2019-04-26 05:38 UTC, xinput123 commented on api/app/controllers/api/API.java
> +        }
我用netty的提供的方法去处理吧

2019-04-26 05:39 UTC, fivesmallq commented on api/app/controllers/api/API.java
> +        }
恩，这种框架提供的基础方法，尽量对细节都处理的好一点。

2019-04-28 01:06 UTC, fivesmallq approved these changes

2019-04-28 01:06 UTC, merged